import Banner from '@/components/home/sections/Banner'
import type { Metadata } from 'next'
import Image from 'next/image'

export const metadata: Metadata = {
  title: 'Something Else',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main >
      <Banner />
    </main>
  )
}
